### ISSUE TITLE
Be able to take quizzes 

### ISSUE THREAD

**Issue by lachlanjc** [lachlanjc/quizapp#19]
**To complete this issue:**
- Create a new HTML file under /pages for a sample view for taking quizzes
- Add proper links to stylesheets and a **new script and stylesheet**
- Write the code (using [this gist](https://gist.github.com/lachlanjc/32ede7e75b441196ec47) as guidance for letting people be able to click on the label or the radio button) for multiple choice and write a response

_just completing part of this is fine, just commit the changes and comment here!_

**Comment by taransamarth** [comment]
Created a page for taking quizzes; working on script/stylesheet.

**Comment by lachlanjc** [comment]
Sounds good! Have you asked about you-know-what yet? (email me if you can't)

**Comment by lachlanjc** [comment]
Awesome work! Thanks so much for diving in and getting started. I’m going to work on a stylesheet for it.

I’m thinking about putting an indicator like TQ’s in the corner showing time, progress, and, if the teacher chooses it, an indicator of correct/incorrect answers.

What’s the deal with the extra numbers in the `for`?

`<input type="radio" name="radio-btn1" id="option_a1"><label for="option_a1">&nbsp 2050</label>`

**Comment by taransamarth** [comment]
Because there are several option_a's. Click on one's title and it selects ALL of the option_a's. It's a temp workaround for now.

**Comment by lachlanjc** [comment]
OK. Also, what about having it save your progress as you go instead of having a button for it?

**Comment by taransamarth** [comment]
Sure. How about a modal that "floats" as you scroll so you can see the time, correct/incorrect, and a save button?

**Comment by lachlanjc** [comment]
Yup!

`display: fixed;`

**Comment by lachlanjc** [comment]
Live development on CodePen at http://codepen.io/lachlanjc/pen/FDJGB

**Comment by lachlanjc** [comment]
I just pushed out a _huge_ update to this. Check it out!

**Comment by taransamarth** [comment]
This issue's needs have been completed.
