### ISSUE TITLE
Add settings page

### ISSUE THREAD

**Issue by lachlanjc** [lachlanjc/quizapp#20]
**To complete this issue:**
- Create a new HTML file under /pages for the settings page (ignore buttons for now because we'll need to guide the user back to their proper dashboard
- Add proper links to stylesheets and a **new script and stylesheet**
- Add a link on both dashboards to the settings page

_just completing part of this is fine, just commit the changes and comment here!_

**Comment by lachlanjc** [comment]
Just in case you were wondering, we'll use this for setting up [Boxcar notifications for teachers](http://boxcar.io/developer) and a few other settings.

**Comment by ghost** [comment]
Submitted a pull request for a background change feature. It's really basic, but could be expanded. Tell me if it's what you want.

**Comment by taransamarth** [comment]
Closed
