### ISSUE TITLE
Create finished quiz modal

### ISSUE THREAD

**Issue by taransamarth** [lachlanjc/quizapp#26]
**To complete this issue for 6 points:**
_This is a modal that will appear after a quiz has been finished. In reality, it's an `iframe` that goes to a page. It needs to show:_
- How long it took to complete the quiz
- Score
- Incorrect answers using a `<table>`

Does anyone else have some ideas for it? Ideas go for 1 point, but only after deemed valid by @lachlanjc or @tns12.

**Comment by taransamarth** [comment]
I finished the page ---- can someone iframe it?

**Comment by lachlanjc** [comment]
Great! Can you go on your email so we can chat there?

**Comment by lachlanjc** [comment]
I think we're done with this, so I'm closing it for now.
